### ISSUE TITLE
CodeSignal Problems

### ISSUE THREAD

**Issue by JorgeGongoraR** [wizelineacademy/sre-bootcamp#1]
Hi

I'm facing an issue when I try to log in CodeSignal to do the code challenge

Evidence:

<img width="1440" alt="Screen Shot 2021-08-14 at 1 28 40" src="https://user-images.githubusercontent.com/26189497/129437524-2a18fa02-e30f-47f2-a067-248472e30aee.png">

I already tried to log in with my gmail account and also GitHub account 

I hope you can help me

**Comment by JuanGQCadavid** [comment]
Hello, I try it with the simpole way, using my email without google Auth and it works, give it a try

**Comment by JorgeGongoraR** [comment]
Was resolved
Thank you.
