### ISSUE TITLE
JWT is wrong in the given example(README.md)

### ISSUE THREAD

**Issue by mistergamarra** [wizelineacademy/sre-bootcamp#2]
Hi Wizeline,

This provided token is not valid I decoded it using this page https://jwt.io/ and I have noticed the payload does not contain the "role".

In addition into the MethodsTest class we have a different JWT token for the same user (admin). so I would like to know which is the right token for the admin user?

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

![image](https://user-images.githubusercontent.com/31901443/129844896-f84d3ba1-8a01-4500-bdee-eafae5b4acf8.png)

**Comment by Mirdrack** [comment]
@aranzanflores we already clarify this on the [issue](https://github.com/wizelineacademy/sre-bootcamp/issues/4) @mistergamarra opened before.
But if you need to clarify something else feel free to reach us again.

Thank you both for the interests.
