### ISSUE TITLE
JWT token in test cases seems having a different 256 bit secret

### ISSUE THREAD

**Issue by mistergamarra** [wizelineacademy/sre-bootcamp#3]
Hi Wizeline,

I am running the unit test but unfortunately both are failing, maybe you provided a wrong 256 bit secret to sign JWT tokens. I have created two additional test and they run successfully using my own data.

![image](https://user-images.githubusercontent.com/31901443/129848971-589cc3c7-10ab-4989-8e11-fd8cd9ffbec2.png)

**Comment by Mirdrack** [comment]
Hello @mistergamarra 

Thank you for letting us know about this and clarify it.

We are glad that you follow that approach to walk around the issue and thank you for help in the other issues.
