### ISSUE TITLE
token issue - assertion in function test_generate_token

### ISSUE THREAD

**Issue by josue-r** [wizelineacademy/sre-bootcamp#4]
Hi team, i agree with some other folks who have raised an issue related to the token creation function. The assertion in file: **test_api.py**, -> function - *test_generate_token* - , the first parameter in assertion (jwt token) seems to have different structure in comparison to the  generated in function - *generate_token* - in file **methods.py**; In this last one, i have replaced values manually in payload and still show different output, this difference is in the 'header' structure of the token, if i use any decode64 tool to get the content i show the below differences:

assertion value header: 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 ({"alg":"HS256","typ":"JWT"})
token generated with values manually replaced (payload):
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9 ({"typ":"JWT","alg":"HS256"})

As you can see above, the 'header' values order are different, therefore unable to pass the assertion. i tried to find any articles related 'header' order manipulation to test the given value but i was not able to find any, therefore my assumption of this issue.

Please note, if i use the token generated from jwt.encode function and replace it in the assertion from function *test_generate_token* in **test_api.py** file, i can pass the test.

Thanks for your feedback....

**Comment by Mirdrack** [comment]
Hi everybody! 

Thank you for your proactivity and for letting us know about this misunderstanding.
We are glad that you were able to look for walk arounds and solve the issue.

We know the code/instructions are always perfectible and we are sorry about this misunderstanding in the readme.
Feel free to update your repository if you consider there is something to be changed. 
Also contact us by email if you have more questions or you need to clarify something else.

I'm tagging all of you to force the notifications @luisfmp @mistergamarra @josue-r 
And thank you for the interest in the challenge.
